// <auto-generated />
using DiscordBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordBot.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20250203103646_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("DiscordBot.Database.Models.DiscordServer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Queue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiscordServers");
                });
#pragma warning restore 612, 618
        }
    }
}
